### ISSUE TITLE
how to build locally

### ISSUE THREAD

**Issue by navinSing** [vkarpov15/nimrod-new#1]
pls help in building and running this locally..

Thanks a lot

**Comment by vkarpov15** [comment]
What issues exactly are you having?

**Comment by navinSing** [comment]
after npm run compile.. 

to run .. // also NOTE : my db is on some other host .. but looks like commander is not used here .. 

nimrod-new$ ./dist/nimrod 
$isNimrodCursor
/tmp/nimrod/node_modules/asyncblock/node_modules/fibers/fibers.js:16
    throw new Error('`'+ modPath+ '.node` is missing. Try reinstalling `node-fibers`?');
    ^

Error: `/tmp/nimrod/node_modules/asyncblock/node_modules/fibers/bin/linux-x64-v8-4.6/fibers.node` is missing. Try reinstalling `node-fibers`?
    at Object.<anonymous> (/tmp/nimrod/node_modules/asyncblock/node_modules/fibers/fibers.js:16:8)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /tmp/nimrod/node_modules/asyncblock/lib/asyncblock.js:13:23
    at handleFiber (/tmp/nimrod/node_modules/asyncblock/lib/asyncblock.js:95:21)
    at asyncblock (/tmp/nimrod/node_modules/asyncblock/lib/asyncblock.js:28:16)

**Comment by vkarpov15** [comment]
Looks like node-fibers is bugging out. Check out instructions for how to install: https://www.npmjs.com/package/fibers . `node-gyp` needs to work, otherwise nimrod will not work.
